### ISSUE TITLE
Error "invalid distance code" with large backups

### ISSUE THREAD

**Issue by josvos** [lclevy/ab_decrypt#2]
ab-decrypt works fine for small .ab files, but for large .ab files, e.g. a backup of 317 MB, I get at some point:

    zlib.error: Error -3 while decompressing data: invalid distance code

The partly written tar output file is ok for the part it already wrote (284 MB in case of the 317 MB backup), but it is incomplete.

This is with ab-decrypt 1.0.0 (pip install in a Pythoin 3.9.12 venv).

**Comment by josvos** [comment]
Sorry wroing packge I think, should be filed to https://github.com/joernheissler/ab-decrypt

**Comment by josvos** [comment]
Wrong package.

**Comment by lclevy** [comment]
Use code from GitHub
